project:
  type: website

website:
  title: "Florida Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Hillsborough.qmd
        text: Hillsborough  # Add the new page here
      - href: Tampa.qmd
        text: Tampa
      - href: Indian.qmd
        text: Indian Creek
      - href: about.qmd
        text: About



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
