project:
  type: website

website:
  title: "Florida Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: tampa.qmd
        text: Tampa
      - href: Hillsborough.qmd
        text: Hillsborough  # Add the new page here

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
