---
title: "Hillsborough"

1. tidycensus::census_api_key("YOUR_CENSUS_API_KEY_HERE", install = TRUE)

---

```{r}
library(tidycensus)
library(tidyverse)
library(sf)
library(leaflet)
library(viridis)
```




```{r}
# Set your Census API key (get one from https://api.census.gov/data/key_signup.html)
census_api_key("YOUR_CENSUS_API_KEY_HERE", install = TRUE)

# Fetch educational attainment data for Hillsborough County, Florida
hillsborough_data <- get_acs(
  geography = "tract",  # Get data at the census tract level
  variables = "DP02_0068P",  # Variable for percentage of population with a Bachelor's degree or higher
  state = "FL",  # Florida
  county = "Hillsborough",  # Hillsborough County
  geometry = TRUE,  # Include spatial geometry for mapping
  year = 2021  # Specify the year of the data
)

# Rename the variable for clarity
hillsborough_data <- hillsborough_data %>%
  rename(pct_bachelors = estimate)

# Create a color palette for the percentage of Bachelor's degrees
pal <- colorNumeric(palette = viridis(100), domain = hillsborough_data$pct_bachelors)

# Create an interactive Leaflet map
leaflet_map <- leaflet(hillsborough_data) %>%
  addTiles() %>%  # Add default OpenStreetMap tiles (street view)
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite View") %>%  # Add satellite view
  addPolygons(
    fillColor = ~pal(pct_bachelors),  # Color polygons by percentage of Bachelor's degree
    fillOpacity = 0.7,  # Polygon opacity
    color = "white",  # Border color
    weight = 1,  # Border width
    popup = ~paste("Tract: ", NAME, "<br>Bachelor's Degree: ", round(pct_bachelors, 2), "%")  # Popup text
  ) %>%
  addLayersControl(
    baseGroups = c("Street View", "Satellite View"),  # Layer control for switching views
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addLegend(
    pal = pal,  # Color palette
    values = ~pct_bachelors,  # Values for the legend
    title = "Bachelor's Degree (%)",  # Legend title
    position = "bottomright"
  ) %>%
  setView(lng = -82.3479, lat = 27.9904, zoom = 10)  # Set initial view to Hillsborough County

# Display the map
leaflet_map
```

